module001/views.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request
from flask_login import login_required, current_user
from sqlalchemy import or_, and_
from models import get_db, User, Course, Follow, ParticipationCode, ParticipationRedeem
import random
import datetime

from module001.forms import *

module001 = Blueprint("module001", __name__,static_folder="static",template_folder="templates")
db = get_db()

@module001.route('/')
@login_required
def module001_index():
    if current_user.profile in ('admin','staff','student'):
        return render_template("module001_index.html",module="module001")
    else:
        flash("Access denied!")
        return redirect(url_for('index'))


@module001.route('/course', methods=['GET','POST'])
@login_required
def module001_course():
    form = CourseForm()
    if request.method == 'POST':


        if current_user.profile in ('student'):

            flash("YOU DONT HAVE PERMISSION")
            return redirect(url_for('index'))


        if form.validate_on_submit():
            if not form.id.data:
                course = Course(name=form.name.data.strip(),
                                institution_name = form.institution_name.data.strip(),
                                user_id=current_user.id)
                db.session.add(course)
                db.session.commit()
                course.code = 'C'+str(course.id)+''.join(random.choice('AILNOQVBCDEFGHJKMPRSTUXZ') for i in range(4))
                newname = form.name.data.strip().replace('-' + course.code,'')
                if '-' + course.code not in newname:
                    course.name = newname + '-' + course.code
                try:
                    db.session.commit()
                    flash("Course created successfully with code: {}".format(course.code))
                    follow = Follow(user_id=current_user.id,
                                    course_id=course.id,
                                    course_code=course.code,
                                    course_name=course.name,
                                    institution_name = course.institution_name)

                    db.session.add(follow)
                    db.session.commit()
                    flash("Curso anadido")
                except:
                    db.session.rollback()
                    flash("Error creating course!")
            else:
                change = 0
                course = Course.query.get(form.id.data)
                newcoursename = form.name.data.strip().replace('-' + course.code,'') + '-' + course.code
                if course.name != newcoursename:
                    course.name = newcoursename
                    change = 1

                newinstitutionname = form.institution_name.data.strip()
                if course.institution_name != newinstitutionname:
                    course.institution_name = newinstitutionname
                    change = 1

                try:
                    if change:
                        db.session.commit()
                        flash("Course  updated successfully!")
                    else:
                        flash("Nothing has changed!")
                except:
                    db.session.rollback()
                    flash("Error updating course!")
                return redirect(url_for('module001.module001_course'))

    elif ('rowid' in request.args):
        course = Course.query.get(request.args['rowid'])
        if not course or course.user_id != current_user.id:
            flash('Error retrieving data for the course {}'.format(request.args['rowid']))
        else:
            form = CourseForm(id=course.id, name=course.name.replace('-' + course.code,''), institution_name = course.institution_name, code=course.code)

    courses = Course.query.filter_by(user_id=current_user.id)
    return render_template("module001_course.html",module="module001", form=form, rows=courses)


from qrcode import QRCode, ERROR_CORRECT_L
@module001.route('/sharing_details',methods=['GET','POST'])
@login_required
def module001_sharing_details():
    qr = QRCode(version=20, error_correction=ERROR_CORRECT_L)
    base_url=request.host
    if request.args.get('itemtype') == 'course':
        course = Course.query.get(request.args.get('rowid'))
        if not course or course.user_id != current_user.id:
            flash("An error has occurred retrieving details for the activity")
            return redirect(url_for('module001.module001_course'))
        qr.add_data("http://{}/course/follow?sharedlink=1&code={}".format(base_url,course.code))
        module,itemtype,item="library","course",course
    else:
        participation = ParticipationCode.query.get(request.args.get('rowid'))
        if not participation or participation.user_id != current_user.id:
            flash("An error has occurred retrieving details for the participation")
            return redirect(url_for('module001.module001_participation_generate'))
        qr.add_data("http://{}/course/participation_redeem?sharedlink=1&code={}".format(base_url,participation.code))
        module,itemtype,item="participation_gerenate","participation",participation
    try:
        qr.make() # Generate the QRCode itself
        im = qr.make_image()
        filename = "./static/qrcodes/{}.png".format(item.code)
        urlfilename = "http://{}/static/qrcodes/{}.png".format(base_url,item.code)
        im.save(filename)
        return render_template('module001_sharing_details.html',module="module001", item=item, itemtype=itemtype,filename=urlfilename,base_url=base_url)
    except:
        return render_template('module001_sharing_details.html',module="module001", item=item, itemtype=itemtype,base_url=base_url)


@module001.route('/follow',methods=['GET','POST'])
@login_required
def module001_follow():
    form = FollowForm()
    unfollow=False
    if request.method == 'POST':
        if form.validate_on_submit():
            course_code = form.code.data
            follow = Follow.query.filter(and_(Follow.course_code==form.code.data,
                                              Follow.user_id==current_user.id)).first()
            if follow:
                flash("You are already following the course {} ".format(course_code))
            else:
                course = Course.query.filter_by(code=form.code.data).first()
                if not course:
                    flash('The code {} is invalid, try again with the correct code.'.format(form.code.data))
                else:
                    follow = Follow(user_id=current_user.id,
                                    course_id=course.id,
                                    course_code=course.code,
                                    course_name=course.name,
                                    institution_name = course.institution_name)
                    try:
                        db.session.add(follow)
                        db.session.commit()
                        flash("You are now following {}".format(course.name))
                    except:
                        db.session.rollback()
                        flash("Error following!")
    elif ('sharedlink' in request.args):
        form=FollowForm(code=request.args.get('code'))

    follows = Follow.query.filter_by(user_id=current_user.id)
    return render_template('module001_follow.html',module="module001", form=form, rows=follows, unfollow=unfollow)

@module001.route('/unfollow',methods=['GET','POST'])
@login_required
def module001_unfollow():
    form = FollowForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            course_code = form.code.data
            follow = Follow.query.filter(and_(Follow.course_code==form.code.data,
                                              Follow.user_id==current_user.id)).first()
            if follow:
                try:
                    db.session.delete(follow)
                    db.session.commit()
                    flash("You are not following {} any longer".format(course_code))
                    return redirect(url_for('module001.module001_follow'))
                except:
                    db.session.rollback()
                    flash("Error unfollowing!")
        flash('Something unusual happened, please try again later')
    else:
        form=FollowForm(code=request.args.get('code'))
    unfollow=True
    follows = Follow.query.filter_by(user_id=current_user.id)

    return render_template('module001_follow.html',module="module001", form=form, rows=follows, unfollow=unfollow)


@module001.route('/participation_generate',methods=['GET','POST'])
@login_required
def module001_participation_generate():
    form = ParticipationCodeForm()
    if request.method == 'POST':
        try:
            if not form.id.data:
                course = Course.query.get(form.course_id.data)
                while(True):
                    participation_code = 'P'+str(form.course_id.data)+''.join(random.choice('AILNOQVBCDEFGHJKMPRSTUXZ') for i in range(4))
                    participation = ParticipationCode.query.filter_by(code=participation_code).first()
                    if not participation:
                        break
                if course:
                    if form.never_expire.data:
                        participation = ParticipationCode(
                                code = participation_code,
                                code_description =  form.code_description.data,
                                code_type = form.code_type.data,
                                user_id = current_user.id,
                                course_id = course.id,
                                course_name = course.name,
                                institution_name = course.institution_name)
                    else:
                        participation = ParticipationCode(
                                code = participation_code,

module001/templates/module001_course.html
{% extends 'module001_base.html' %}

{% block content %}
   <nav class="navbar navbar-default">
      <div class="container-fluid">

        <ul class="nav navbar-nav">


              <li><a href={{url_for('module001.module001_index')}}>Home</a></li>
              <li><a href={{url_for('module001.module001_course')}}>Create</a></li>
              <li><a href={{url_for('module001.module001_follow')}}>Following</a></li>
              <li><a href={{url_for('module001.module001_participation_generate')}}>Participation</a></li>
              <li><a href={{url_for('module001.module001_participation_redeem')}}>Redeemed</a></li>

        </ul>
      </div>
    </nav>

    <div class="container">
      <form class="form-signin" method="POST" action="{{url_for('module001.module001_course')}}">
        <h2 class="form-signin-heading"> Course / Institution </h2>
        {{ form.hidden_tag() }}
    	{{ wtf.form_field(form.id,readonly="readonly") }}
    	{{ wtf.form_field(form.name) }}
    	{{ wtf.form_field(form.institution_name) }}
    	{{ wtf.form_field(form.code,readonly="readonly") }}

       <button class="btn btn-lg btn-primary btn-block" type="submit"> Create or Update library </button>
       </form>

    <br>
      <div class="table-responsive">
        <table id="myTable" class="table table-striped">
          <thead>
            <tr>
              <th>Edit</th>
              <th>Grades</th>
              <th>Share Code</th>
              <th>Institution Name</th>
              <th>User id</th>
              <th>Date Created</th>
              <th>Date Modified</th>

            </tr>
          </thead>
          <tbody>
            {% for row in rows %}
            <tr>
               <td> <a><form action="{{url_for('module001.module001_course')}}" method="GET">
                   <input type="submit" value={{ row.id }} name="rowid">
               </form> </a></td>

               <td> <a><form action="" method="GET">
                   <input type="hidden" value={{ row.id }} name="rowid">
                   <input type="submit" value={{ row.name }} name="coursename">
               </form> </a></td>

               <td> <a><form action="{{url_for('module001.module001_sharing_details')}}" method="GET">
                   <input type="hidden" value={{ row.id }} name="rowid">
                   <input type="hidden" value="course" name="itemtype">
                   <input type="submit" value={{ row.code }} name="code">
               </form> </a></td>

                <td>{{ row.institution_name }}</td>

                <td> <a><form action="/profile" method="GET">
                   <input type="submit" value={{ row.user_id }} name="rowid">
               </form> </a></td>
                <td>{{ row.date_created }}</td>
                <td>{{ row.date_modified }}</td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}

module001/templates/module001_follow.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <ul class="nav navbar-nav">


              <li><a href={{url_for('module001.module001_index')}}>Home</a></li>
              <li><a href={{url_for('module001.module001_course')}}>Create</a></li>
              <li><a href={{url_for('module001.module001_follow')}}>Following</a></li>
              <li><a href={{url_for('module001.module001_participation_generate')}}>Participation</a></li>
              <li><a href={{url_for('module001.module001_participation_redeem')}}>Redeemed</a></li>

        </ul>
      </div>
    </nav>


    <div class="container">


        {% if unfollow %}
           <form class="form-signin" method="POST" action="{{url_for('module001.module001_unfollow')}}">
            {{ form.hidden_tag() }}
        	{{ wtf.form_field(form.code) }}
             <button class="btn btn-lg btn-warning btn-block" type="submit">Unfollow</button>
           </form>
          </form>
        {% else %}
           <form class="form-signin" method="POST" action="{{url_for('module001.module001_follow')}}">
            {{ form.hidden_tag() }}
        	{{ wtf.form_field(form.code) }}
            <button class="btn btn-lg btn-primary btn-block" type="submit"> Follow </button>
           </form>
        {% endif %}


        <br>
          <div class="table-responsive">
            <table id="myTable" class="table table-striped">
              <thead>
                <tr>
                  <th>Edit</th>
                  <th>Course Name</th>
                  <th>Course Code</th>
                  <th>Institution Name</th>
                  <th>User id</th>
                  <th>Date Created</th>
                  <th>Date Modified</th>

                </tr>
              </thead>
              <tbody>
                {% for row in rows %}
                <tr>

                   <td> <a><form action="{{url_for('module001.module001_unfollow')}}" method="GET">
                       <input type="submit" value={{ row.course_code }} name="code">
                   </form> </a></td>

                    <td>{{ row.course_name }}</td>
                    <td>{{ row.course_code }}</td>
                    <td>{{ row.institution_name }}</td>

                    <td> <a><form action="/profile" method="GET">
                       <input type="submit" value={{ row.user_id }} name="rowid">
                   </form> </a></td>
                    <td>{{ row.date_created }}</td>
                    <td>{{ row.date_modified }}</td>

                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

    </div>
{% endblock %}

module001/templates/module001_index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
   <nav class="navbar navbar-default">
      <div class="container-fluid">

        <ul class="nav navbar-nav">


              <li><a href={{url_for('module001.module001_index')}}>Home</a></li>
              <li><a href={{url_for('module001.module001_course')}}>Create</a></li>
              <li><a href={{url_for('module001.module001_follow')}}>Following</a></li>
              <li><a href={{url_for('module001.module001_participation_generate')}}>Participation</a></li>
              <li><a href={{url_for('module001.module001_participation_redeem')}}>Redeemed</a></li>

        </ul>
      </div>
    </nav>

    <div>

        WELCOME

    </div>
{% endblock %}

module001/templates/module001_participation_generate.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
  <nav class="navbar navbar-default">
      <div class="container-fluid">

        <ul class="nav navbar-nav">


              <li><a href={{url_for('module001.module001_index')}}>Home</a></li>
              <li><a href={{url_for('module001.module001_course')}}>Create</a></li>
              <li><a href={{url_for('module001.module001_follow')}}>Following</a></li>
              <li><a href={{url_for('module001.module001_participation_generate')}}>Participation</a></li>
              <li><a href={{url_for('module001.module001_participation_redeem')}}>Redeemed</a></li>

        </ul>
      </div>
    </nav>
<div class="container">

       <form class="form-signin" method="POST" action="{{url_for('module001.module001_participation_generate')}}">
        {{ form.hidden_tag() }}
    	{{ wtf.form_field(form.id,readonly="readonly") }}
    	{{ wtf.form_field(form.code,readonly="readonly") }}
    	{{ wtf.form_field(form.code_description) }}
    	{{ wtf.form_field(form.course_id) }}
    	{{ wtf.form_field(form.code_type) }}
    	{{ wtf.form_field(form.never_expire) }}
    	{{ wtf.form_field(form.date_expire) }}
    	{{ wtf.form_field(form.time_expire) }}

        <button class="btn btn-lg btn-primary btn-block" type="submit"> Create or Update Participation Point </button>
       </form>

        <br>
          <div class="table-responsive">
            <table id="myTable" class="table table-striped">
              <thead>
                <tr>
                  <th>All</th>

                  <th>Edit</th>
                  <th>Share Participation Code</th>
                  <th>Description</th>
                  <th>Code Type</th>
                  <th>Course Name</th>
                  <th>Institution Name</th>
                  <th>Expiring Date</th>
                  <th>Date Created</th>
                  <th>Date Modified</th>
                </tr>
              </thead>
              <tbody>
                {% for row in rows %}
                <tr>

                   <td> <a><form action="{{url_for('module001.module001_participation_generate')}}" method="GET">
                       <input type="hidden" value={{ row.id }} name="rowid">
                       <input type="hidden" value="redeems" name="redeems">
                       <input type="submit" value="+" name="+">
                   </form> </a></td>

                   <td> <a><form action="{{url_for('module001.module001_participation_generate')}}" method="GET">
                       <input type="submit" value={{ row.id }} name="rowid">
                   </form> </a></td>

                   <td> <a><form action="{{url_for('module001.module001_sharing_details')}}" method="GET">
                       <input type="hidden" value={{ row.id }} name="rowid">
                       <input type="hidden" value="participation" name="itemtype">
                       <input type="submit" value={{ row.code }} name="code">
                   </form> </a></td>
                    <td>{{ row.code_description }}</td>
                    <td>{{ row.code_type }}</td>
                    <td>{{ row.course_name }}</td>
                    <td>{{ row.institution_name }}</td>

                    <td>{{ row.date_expire }}</td>
                    <td>{{ row.date_created }}</td>
                    <td>{{ row.date_modified }}</td>


                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

    </div>

    <script>
            //$("#never_expire").hide();
/*			$(document).ready( // run after the document is loaded
				function(){ // anonymous function
                    $("#never_expired").click(function() {
                        $("#never_expire").hide()
                    })
				}
			)
*/
            $(document).ready(function() {
                //set initial state.

                $('#never_expired').change(function() {
                    if(this.checked) {
                        var returnVal = confirm("Are you sure?");
                        $(this).prop("checked", returnVal);
                    }
                });
            });
    </script>

{% endblock %}

module001/templates/module001_participation_redeem.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <ul class="nav navbar-nav">


              <li><a href={{url_for('module001.module001_index')}}>Home</a></li>
              <li><a href={{url_for('module001.module001_course')}}>Create</a></li>
              <li><a href={{url_for('module001.module001_follow')}}>Following</a></li>
              <li><a href={{url_for('module001.module001_participation_generate')}}>Participation</a></li>
              <li><a href={{url_for('module001.module001_participation_redeem')}}>Redeemed</a></li>

        </ul>
      </div>
    </nav>
    <div class="container">

        {% if unfollow %}
           <form class="form-signin" method="POST" action="{{url_for('module001.module001_participation_redeem_delete')}}">
            {{ form.hidden_tag() }}
        	{{ wtf.form_field(form.code) }}
             <button class="btn btn-lg btn-warning btn-block" type="submit">Remove</button>
           </form>
          </form>
        {% else %}
           <form class="form-signin" method="POST" action="{{url_for('module001.module001_participation_redeem')}}">
            {{ form.hidden_tag() }}
        	{{ wtf.form_field(form.code) }}
            <button class="btn btn-lg btn-primary btn-block" type="submit"> Redeem </button>
           </form>
        {% endif %}

        <br>
          <div class="table-responsive">
            <table id="myTable" class="table table-striped">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Participation Code</th>
                  <th>Description</th>
                  <th>Course Name</th>
                  <th>Institution Name</th>
                  <th>Date Created</th>
                  <th>Date Modified</th>
                </tr>
              </thead>
              <tbody>
                {% for row in rows %}
                <tr>

                   <td> <a><form action="{{url_for('module001.module001_participation_redeem')}}" method="GET">
                       <input type="submit" value={{ row.id }} name="rowid">
                   </form> </a></td>

                    <td>{{ row.participation_code }}</td>
                    <td>{{ row.code_description }}</td>
                    <td>{{ row.course_name }}</td>
                    <td>{{ row.institution_name }}</td>

                    <td>{{ row.date_created }}</td>
                    <td>{{ row.date_modified }}</td>


                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

    </div>
{% endblock %}

module001/templates/module001_sharing_details.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <ul class="nav navbar-nav">


              <li><a href={{url_for('module001.module001_index')}}>Home</a></li>
              <li><a href={{url_for('module001.module001_course')}}>Create</a></li>
              <li><a href={{url_for('module001.module001_follow')}}>Following</a></li>
              <li><a href={{url_for('module001.module001_participation_generate')}}>Participation</a></li>
              <li><a href={{url_for('module001.module001_participation_redeem')}}>Redeemed</a></li>

        </ul>
      </div>
    </nav>
    <div class="container">
        {% if itemtype == "course" %}
            <h1> Joinning details: </h1>
            <h2> {{ item.name }} </h2>
             <ul>
              <li>Code: {{ item.code }}
              (join by entering the code here: <a href="http://{{base_url}}/course/follow" target="_blank">http://{{base_url}}/course/follow</a>)</li>
              <li>Direct link: <a href="http://{{base_url}}/course/follow?sharedlink=1&code={{item.code}}" target="_blank">http://{{base_url}}/course/follow?sharedlink=1&code={{ item.code }}</a></li>
              {% if filename %}
                  <li><img  src={{filename}} alt="" style="width: 40%; height: auto;"></li>
              {% endif %}

            </ul>
        {% elif itemtype == "participation" %}
            <h1> Redeeming details: </h1>
            <h2> {{ item.code_description }} </h2>
             <ul>
              <li>Code: {{ item.code }}
              (redeem by entering the code here: <a href="http://{{base_url}}/course/participation_redeem" target="_blank">http://{{base_url}}/course/participation_redeem</a>)</li>
              <li>Direct link: <a href="http://{{base_url}}/course/participation_redeem?sharedlink=1&code={{item.code}}" target="_blank">http://{{base_url}}/course/participation_redeem?sharedlink=1&code={{ item.code }}</a></li>
              {% if filename %}
                  <li><img  src={{filename}} alt="" style="width: 40%; height: auto;"></li>
              {% endif %}
            </ul>
        {% endif %}

    </div>
{% endblock %}